// Copyright (c) Privasys. All rights reserved.
// Licensed under the GNU Affero General Public License v3.0. See LICENSE file for details.

package ledger

import (
	"encoding/hex"
	"fmt"
	"testing"
)

// Cross-implementation compatibility: these vectors were generated by
// the Rust reference implementation (enclave-os-mini
// crates/enclave-os-merkle) running the identical scenario. A Go store
// sharing the commitment key must reproduce every root byte for byte,
// and Rust-generated proofs must verify here.
//
// Generator: a #[test] against MerkleStore<MemBackend> with
// ck[i] = i, sk[i] = 0xA0 + i, printing (version, root) after each
// batch and the encoded proofs at the final root.

const (
	goldenRoot1 = "b8720446c3642c5bd577aa53037aca191f56c501b970a27615883e6d3cf6d293"
	goldenRoot2 = "8a46f27b42fa87ea9d775ebbff9baa7cf2ee8a45b33b2c99793c3a53b91e8296"
	goldenRoot3 = "4548a48a342960e9a51d46f46c756911b4816ac3a4bf5aa442f339f6ce7696f0"
	goldenRoot4 = "3fa0445343dbe12a68aa2552902ec55063e6b923ee219bcdefb61cc4aae82b86"
	goldenRoot5 = "0eae295f13c47f2efeb41cef9006d5ee1a6610d2087faaff7d061ac7c3b83a96"

	goldenProofAlice  = "01a50421302d96ab9afe8354169059d230ab98180548c9184537141bd7e804a454e9503b8f1a90c290e91be34962e29eded41f9460bfe08b8814d4ee1e7cd6e0b40600bcede1d7496945e5260585210f323a882aeb792cfd43f00dea07ac46cc8da4ec740bb7f568947f5e8b69c9d94229c445daf7f1146e759d706b3362de8a4ca9126aee73418ff45f7e3bdbc747289af7f74a33089e52219ad77a680ced9563e76d85c51660c2139ce21d0f676a3a6345d443b8bc9a9ad8b4be8470204ae5fd106395ffeabe84099fa3adfdbf151b5808d3071626bc68d69bc6e5a0d111bbf32308d412ac83efc5d5aff8a9e5938b0526a73cf852106170fc12c3b52a326e46b569"
	goldenProofAbsent = "015e173bbc21ccdbb6739f7a668a1d3665311d13dccfb5e134d85813cf48a7dc96c47de7bfaa61820af849138ca1a40ff2c0a3d2535b9d953327a134ad7de7eeaf0600461d1cd5a9089e9cfbbb09e0a74771f617c1b7e5ab57c7af9d4c3a3d8d7571daa2c85481cbe22a2f0175bde912ec11eb6661aebb789d0549365be6edb0354742d1383e24a1d0e57af72344d84da7b1316925176994fa801f02d1fe333955f8f8dc0e6813984af5296376cfddf10dc6b9b4f8fe68930344edfd9272333803b0fad306b987452eb153f310ec5374890306980f09ba6478892634e89c2b7acbada032e0fce68940cce2fbd9d641c9369a2843113b0e7b26b1dc63327fc3b06607fd"
)

func goldenKeys() ([KeySize]byte, [KeySize]byte) {
	var ck, sk [KeySize]byte
	for i := 0; i < KeySize; i++ {
		ck[i] = byte(i)
		sk[i] = byte(0xA0 + i)
	}
	return ck, sk
}

func mustHexRoot(t *testing.T, s string) Hash {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil || len(b) != HashSize {
		t.Fatalf("bad golden root %q", s)
	}
	var h Hash
	copy(h[:], b)
	return h
}

func TestRustCompatibilityRoots(t *testing.T) {
	ck, sk := goldenKeys()
	s, err := Create(NewMemBackend(), ck, sk)
	if err != nil {
		t.Fatal(err)
	}

	check := func(step string, want string, root Hash, version, wantVersion uint64) {
		t.Helper()
		if version != wantVersion {
			t.Fatalf("%s: version %d, want %d", step, version, wantVersion)
		}
		if root != mustHexRoot(t, want) {
			t.Fatalf("%s: root %x, want %s", step, root, want)
		}
	}

	r, v, err := s.PutBatch([]Op{
		Put([]byte("alice"), []byte("1000")),
		Put([]byte("bob"), []byte("250")),
	})
	if err != nil {
		t.Fatal(err)
	}
	check("step1", goldenRoot1, r, v, 1)

	r, v, err = s.PutBatch([]Op{
		Put([]byte("carol"), []byte("7")),
		Put([]byte("dave"), []byte{}),
		Put([]byte("alice"), []byte("1001")),
	})
	if err != nil {
		t.Fatal(err)
	}
	check("step2", goldenRoot2, r, v, 2)

	r, v, err = s.PutBatch([]Op{
		Del([]byte("bob")),
		Put([]byte("eve"), []byte("zzz")),
	})
	if err != nil {
		t.Fatal(err)
	}
	check("step3", goldenRoot3, r, v, 3)

	var ops []Op
	for i := 0; i < 100; i++ {
		ops = append(ops, Put(
			[]byte(fmt.Sprintf("key-%03d", i)),
			[]byte(fmt.Sprintf("value-%03d", i))))
	}
	r, v, err = s.PutBatch(ops)
	if err != nil {
		t.Fatal(err)
	}
	check("step4", goldenRoot4, r, v, 4)

	var dels []Op
	for i := 0; i < 100; i += 2 {
		dels = append(dels, Del([]byte(fmt.Sprintf("key-%03d", i))))
	}
	r, v, err = s.PutBatch(dels)
	if err != nil {
		t.Fatal(err)
	}
	check("step5", goldenRoot5, r, v, 5)

	// A Go-generated proof for the same state matches the Rust encoding
	// byte for byte (the descent is deterministic).
	proofAlice, err := s.Prove([]byte("alice"))
	if err != nil {
		t.Fatal(err)
	}
	if hex.EncodeToString(proofAlice.Encode()) != goldenProofAlice {
		t.Fatal("alice proof encoding differs from the Rust reference")
	}
}

func TestRustCompatibilityProofs(t *testing.T) {
	// Rust-generated proofs verify against the Rust-generated root,
	// through the Go verifier, including the value commitment check.
	ck, sk := goldenKeys()
	s, err := Create(NewMemBackend(), ck, sk)
	if err != nil {
		t.Fatal(err)
	}
	root := mustHexRoot(t, goldenRoot5)

	rawInc, err := hex.DecodeString(goldenProofAlice)
	if err != nil {
		t.Fatal(err)
	}
	inc, err := DecodeProof(rawInc)
	if err != nil {
		t.Fatalf("decode rust inclusion proof: %v", err)
	}
	ok, err := s.VerifyValue(&root, []byte("alice"), []byte("1001"), inc)
	if err != nil || !ok {
		t.Fatalf("rust inclusion proof failed in go: %v", err)
	}
	if ok, _ := s.VerifyValue(&root, []byte("alice"), []byte("forged"), inc); ok {
		t.Fatal("rust proof verified a forged value")
	}

	rawAbs, err := hex.DecodeString(goldenProofAbsent)
	if err != nil {
		t.Fatal(err)
	}
	abs, err := DecodeProof(rawAbs)
	if err != nil {
		t.Fatalf("decode rust absence proof: %v", err)
	}
	ok, err = s.VerifyAbsent(&root, []byte("absent-key"), abs)
	if err != nil || !ok {
		t.Fatalf("rust absence proof failed in go: %v", err)
	}
}
